<?php
return [
    'WEBSITE_URL'                   => 'https://mittlearn.com/',

    // 'MAX_FILE_SIZE'                 => 5120, // 5MB
    'MAX_FILE_SIZE'                 => 204800, // 5MB

    'COURSES_FILTER_BY_ACCESS_CODE' => 0, // 1 for get courses by access code and 0 for by assigned classes

    'FLASH_CONNECTION'              => '🔌 Oops! Connection lost. Reconnect and let’s get you back on track! 🌐',
    'FLASH_SUCCESS_LOGIN_ALERT'     => '🚀 Hold on! You’re not logged in yet. Log in now and continue the magic! ✨',
    'FLASH_SUCCESS_LOGIN'           => '🎉 Welcome aboard! You’ve successfully logged in! 🚀',
    'FLASH_SUCCESS_LOGOUT'          => '👋 You’ve successfully logged out. See you again soon! 🌟',
    'FLASH_INVALID_CREDENTIAL'      => '🚫 Uh-oh! Those credentials don’t match. Try again! 🛠️',
    'FLASH_INVALID_EMAIL_ADDRESS'   => '📧 Oops! That email doesn’t look right. Double-check and retry!',
    'FLASH_EMAIL_VERIFY_1'          => '✅ Woohoo! Your email is verified. Let’s get started! 🎉',
    'FLASH_EMAIL_VERIFY_2'          => '🏫 Success! Your school verification is complete. 🚀',
    'FLASH_EMAIL_VERIFY_0'          => '❌ Hmm, the email ##EMAIL## isn’t verified yet. Give it another shot! 📩',
    'FLASH_EMAIL_ADDRESS_EXIST'     => '📬 This email is already taken! Try logging in or use another. 😊',
    'FLASH_USERNAME_EXIST'          => '🤔 Looks like this username is already in use. Try another one!',
    'FLASH_MOBILE_NUMBER_EXIST'     => '📱 This mobile number is already registered. Got another?',
    'FLASH_ACC_CREATE_0'            => '🚫 Uh-oh! Something went wrong while creating your account. Please try again! 🔄',
    'FLASH_ACC_CREATE_1'            => '🎉 Success! Your account is ready. Welcome aboard! 🚀',
    'FLASH_RESET_PASS_SUCCESS'      => '🔒 Password reset successful! Log in to continue your journey! 🌟',
    'FLASH_RESET_PASS_FAIL'         => '⏳ Time’s up! That reset link has expired or isn’t valid. Try again!',
    'FLASH_ALL_FIELD_REQUIRED'      => '⚠️ Heads up! All fields are required to proceed. Let’s fill them out! 📝',
    'FLASH_FILL_REQUIRED_FIELD'     => '📋 Don’t leave blanks! Fill in all the required fields to continue. ✍️',
    'FLASH_NPASS_CPASS_NOT_MATCH'   => '🔑 Uh-oh! Your new password and confirmation don’t match. Try again! 🔁',
    'FLASH_INVALID_OLD_PASS'        => '🚫 Incorrect old password. Let’s double-check that! 🔍',
    'FLASH_CPASS_LENGTH'            => "🔑 Password alert! It must be at least 6 characters long for added security.",
    'FLASH_REC_ADD_1'               => '🎉 Success! Your record has been added! Keep up the great work! 🌟',
    'FLASH_REC_ADD_0'               => '🚫 Oops! We couldn’t add your record. Let’s try again! 🔄',
    'FLASH_REC_UPDATE_1'            => '✅ Update successful! Your record has been refreshed. 🚀',
    'FLASH_REC_UPDATE_0'            => '🚫 Update failed! Let’s give it another go. 🔄',
    'FLASH_REC_DELETE_1'            => '🗑️ Done! Record successfully deleted. 🚀',
    'FLASH_REC_DELETE_0'            => '⚠️ Deletion failed! Something went wrong. Please retry. 🔄',
    'FLASH_TRY_CATCH'               => '🚧 Uh-oh! Something unexpected happened. We’re on it! 🛠️',
    'FLASH_STATUS'                  => '✅ Status updated successfully! Stay awesome! 🎉',
    'FLASH_ASSIGN_CODE_USER'        => '🔑 Access Codes assigned! Time to unlock the magic! ✨',
    'FLASH_REC_REMOVE_1'            => '✨ Record successfully removed! 🎉',
    'FLASH_REC_REMOVE_0'            => '❌ Oops! Record removal failed. Give it another shot! 🔄',
    'FLASH_REC_RESET_1'             => '🔄 Record reset successfully! 🚀',
    'FLASH_REC_RESET_0'             => '⚠️ Unable to reset the record. Please try again! ⏳',
    'FLASH_REC_NOT_FOUND'           => '🔍 Record not found. Let’s double-check and try again! 🧐',
    'FLASH_PROFILE_UPDATE_1'        => '👤 Profile updated successfully! 💪',
    'FLASH_INVALID_PARAMS'          => '⚠️ Invalid parameters provided. Please recheck and try again! 🔁',
    'FLASH_NOT_ALLOW_URL'           => '🚫 Access denied! You’re not allowed to request this URL. 🛑',
    'FLASH_PAGE_NOT_ALLOWD'         => '⛔ Authorization required! You don’t have permission to access this section. 🔐',
    'FLASH_EMAIL_SUBS_1'            => '📬 Subscribed to notifications successfully! Stay tuned! ✨',
    'FLASH_EMAIL_SUBS_LIMIT'        => '📩 Daily limit reached! Only 20 subscriptions allowed per day. ⏳',
    'FLASH_CONTACT_US_1'            => '🙏 Thank you! Your message was sent successfully. We’ll get back to you soon! 💌',
    'FLASH_CONTACT_US_0'            => '❌ Message delivery failed! Please try again later. 🌧️',
    'FLASH_ACCOUNT_DEACTIVATED'     => '❌ Your account is deactivated. Please contact the Mittlearn team. 🌧️',

    'FLASH_PLANNER_AS_COMPLETED' => '🦸 Planner saved! Another mission accomplished! 💥📝',

    'SCHOOL_VERIFY' => 'School verified successfully',

    'SMS_SUCCESS' => 'SMS sent successfully!',

    'API_MSG'                       => [
        'CALL_SUCCESS'             => 'Success',
        'CALL_FAILED'              => 'Failed',
        'SERVER_ERROR'             => 'Server Error',
        'UNAUTHORISED'             => 'User not authorized',
        'NOT_FOUND_USER'           => 'User not found',
        'VALIDATION_ERROR'         => 'Validation Error',
        'ALREADY_ACCOUNT_ERROR'         => 'You already have an account. Please log in to proceed',
        'INVALLID_TOKEN'           => 'Invallid Token',
        'USER_NOT_FOUND'           => 'User not exist',

        'REQ_USER_ID'              => 'User id is required',

        'SUCCESS_LOGOUT'           => 'Successfully logged out !',
        'FAILED_LOGOUT'            => 'Logged out fialed !',
        'EMAIL_ADDRESS_EXIST'      => 'Email address already exist.',
        'MOBILE_NO_EXIST'          => 'Mobile no already exist.',
        'MOBILE_NO_VERIFY'         => 'Please verify your Mobile no',
        'ACCOUNT_CREATE_SUCCESS'   => 'Your account created successfully',
        'ACCOUNT_LOGGIN_SUCCESS'   => 'Loggedin successfully',
        'ACCOUNT_LOGGIN_FAILED'    => 'Loggedin failed',
        'ADMIN_ACCOUNT_LOGGIN_FAILED'    => 'Super Admin needs to log in through the web portal',
        'OTP_VERIFIED_SUCCESS'     => 'OTP verified successfully',
        'OTP_SENT_SUCCESS'         => 'OTP sent successfully on your ##OTP_ON##',
        'OTP_INVALID_EXPIRED'      => 'OTP invalid or expired',
        'OTP_SENT_FAILED'          => 'Failed to sent otp',
        'REGISTRAION_ERROR'        => 'Failed to register user',
        'INVALID_CREDENTIAL'       => 'Invalid login credentials',
        'PASSWORD_RESET_SUCCESS'   => 'Password reset successfully',
        'PASSWORD_INCORRECT'       => 'Password is incorrect',

        'FEEDBACK_ADD_SUCCESS'     => 'Your feedback submitted successfully',
        'FEEDBACK_ADD_FAILED'      => 'Your feedback submission failed',

        'REC_NOT_FOUND'            => 'Record not found',
        'REC_ADD_SUCCESS'          => 'Record successfully added!',
        'REC_ADD_FAILED'           => 'Record not added.Try again!',
        'REC_UPDATE_SUCCESS'       => 'Record successfully updated!',
        'REC_UPDATE_FAILED'        => 'Record not updated.Try again!',
        'REC_DELETE_SUCCESS'       => 'Record successfully deleted!',
        'REC_FETCHED_SUCCESS'      => 'Record successfully fetched!',
        'REC_DELETE_FAILED'        => 'Record not deleted.Try again!',
        'REC_REMOVE_SUCCESS'       => 'Record successfully removed!',
        'REC_REMOVE_FAILED'        => 'Record not removed.Try again!',

        'ACCESS_CODE_ALREADY_USED' => 'You are already using an Access Code.',
        'ACCESS_CODE_VALLIDATED'   => 'Access Code validated and activated successfully.',
        'ACCESS_CODE_INVALLID'     => 'Invalid or already used Access Code.',
    ],
    'PAPER_SIZE'                    => [
        'Letter'           => 'Letter',
        'Legal'            => 'Legal',
        'A4'               => 'A4',
        'C'                => 'C',
        'D'                => 'D',
        'E'                => 'E',
        'Executive'        => 'Executive',
        'A3'               => 'A3',
        'A5'               => 'A5',
        'B4'               => 'B4',
        'B5'               => 'B5',
        'Folio'            => 'Folio',
        'Quarto'           => 'Quarto',
        'Statement'        => 'Statement',
        'Tabloid'          => 'Tabloid',
        'Ledger'           => 'Ledger',
        'Custom'           => 'Custom',
        'JapanesePostcard' => 'Japanese Postcard',
        'A6'               => 'A6',
        'B6'               => 'B6',
        'Standard10x11'    => 'Standard 10x11',
        'Standard15x11'    => 'Standard 15x11',
        'InviteEnvelope'   => 'Invite Envelope',
        'LetterExtra'      => 'Letter Extra',
        'LegalExtra'       => 'Legal Extra',
        'TabloidExtra'     => 'Tabloid Extra',
        'A4Extra'          => 'A4 Extra',
        'LetterPlus'       => 'Letter Plus',
        'A4Plus'           => 'A4 Plus',
        'B5Extra'          => 'B5 Extra',
        'A2'               => 'A2',
        'A3Extra'          => 'A3 Extra',
        'A5Extra'          => 'A5 Extra',
        'B5Plus'           => 'B5 Plus',
        'A0'               => 'A0',
        'A1'               => 'A1',
        'Standard12x11'    => 'Standard 12x11',
        'Note'             => 'Note',
        'Envelope9'        => 'Envelope #9',
        'Envelope10'       => 'Envelope #10',
        'Envelope11'       => 'Envelope #11',
        'Envelope12'       => 'Envelope #12',
        'Envelope14'       => 'Envelope #14',
        'EnvelopeC5'       => 'Envelope C5',
        'EnvelopeDL'       => 'Envelope DL',
        'EnvelopeB4'       => 'Envelope B4',
        'EnvelopeB5'       => 'Envelope B5',
        'EnvelopeB6'       => 'Envelope B6',
        'EnvelopeItaly'    => 'Envelope Italy',
    ],
    'FONT_FAIMLY'                   => [
        'Arial'   => ' Arial',
        'Poppins' => ' Poppins',
        'Nunito'  => ' Nunito',
    ],
    'FONT_COLOR'                    => [
        'black' => 'black',
    ],
    'SITE_LOGO'                     => 'frontend/images/mittlearn-logo.svg',
    'API_STATUS_CODE'               => [
        'SUCCESS'      => 200,
        'ERROR'        => 201,
        'UNAUTHORISED' => 202,
    ],
    'PAGINATION'                    => [
        'default' => 10,
        'api'     => 10,
    ],
    'PLANNER_VISIBILTY'                    => [
        'daily' => 'Daily',
        'weekly' => 'Weekly',
        'fortnightly' => 'Fortnightly',
        'monthly' => 'Monthly',
    ],
    'GENDER'                        => [
        'Male'   => 'Male',
        'Female' => 'Female',
        'Other'  => 'Other',
    ],
    'CUSTOMER_TYPE'                        => [
        'new'   => 'New',
        'exisiting' => 'Exisiting',
    ],
    'ONLINE_CLASS_STATUS'           => [
        'all'      => 'All',
        'ongoing'  => 'Ongoing',
        'past'     => 'Past',
        'upcoming' => 'Upcoming',
    ],
    'STATUS_LIST'                   => [
        1 => 'Active',
        0 => 'Inactive',
    ],
    'PAPER_TYPE' => [
        'online' => 'Online',
        'offline' => 'Offline',
    ],
    'PORTED_LIST' => [
        true => 'Already In LMS',
        false => 'Not in LMS',
    ],
    'QUESTION_ORDER_TYPE'              => [
        'fixed' => 'Fixed',
        'shuffled' => 'Shuffled',
    ],
    'FEES_TYPE'                     => [
        'classwise'   => 'Class Wise',
        'studentwise' => 'Student Wise',
    ],
    'FEES_DURATION_TYPES'           => [
        'monthly'   => 'Monthly',
        'quarterly' => 'Quarterly',
        'yearly'    => 'Yearly',
    ],
    'TEST_TYPE'                     => [
        1 => 'Online',
        0 => 'Offline',
    ],
    'LANDING_UI'                    => [
        'mittlearn' => 'Mittlearn Student Portal',
        'mittbunny' => 'Pre-Primary Student Portal',
    ],
    'REPLIED_STATUS'                => [
        1 => 'Replied',
        0 => 'Not-Replied',
    ],
    'SECTION'                       => [
        'A' => 'A',
        'B' => 'B',
        'C' => 'C',
        'D' => 'D',
        'E' => 'E',
        'F' => 'F',
        'G' => 'G',
        'H' => 'H',
        'I' => 'I',
        'J' => 'J',
        'K' => 'K',
    ],
    'YES_NO'                        => [
        1 => 'Yes',
        0 => 'No',
    ],
    'COM_PACKAGE'                        => [
        0 => 'Mittlearn',
        1 => 'Talent Box ',
        'all' => 'Both',
    ],
    'IS_CLUBABLE'                   => [
        0 => 'No',
        1 => 'Yes',
    ],
    'CONTENT_LANGUAGE'                        => [
        'bilingual' => 'Bi-lingual',
        'english' => 'English',
    ],
    'VIDEO_VIEW_TYPE'                        => [
        'demo' => 'Demo',
        'product' => 'Product',
        'both' => 'Both',
    ],
    'MONTH_LIST'                    => [
        '1'  => 'January',
        '2'  => 'February',
        '3'  => 'March',
        '4'  => 'April',
        '5'  => 'May',
        '6'  => 'June',
        '7'  => 'July',
        '8'  => 'August',
        '9'  => 'September',
        '10' => 'October',
        '11' => 'November',
        '12' => 'December',
    ],
    'PERMISSION_CATEGORIES'         => [
        'adminAuth'      => 'AdminAuth',
        'frontPage'      => 'FrontPage',
        'permissions'    => 'Permissions',
        'plans'          => 'Plans',
        'blog'           => 'Blog',
        'dashboard'      => 'Dashboard',
        'users'          => 'Users',
        'homePage'       => 'HomePage',
        'instructor'     => 'Instructor',
        'testimonial'    => 'Testimonial',
        'emailTemplate'  => 'EmailTemplate',
        'category'       => 'Category',
        'settings'       => 'Settings',
        'course'         => 'Course',
        'coupon'         => 'Coupon',
        'board'          => 'Board',
        'class'          => 'Class',
        'level'          => 'Level',
        'language'       => 'Language',
        'lesson'         => 'Lesson',
        'subject'        => 'Subject',
        'medium'         => 'Medium',
        'bookSeries'     => 'BookSeries',
        'login'          => 'Login',
        'home'           => 'Home',
        'register'       => 'Register',
        'forgotPassword' => 'ForgotPassword',
        'resetPassword'  => 'ResetPassword',
    ],
    'PERMISSION_FOR_LIST'           => [
        'web' => 'Web',
        'app' => 'App',
    ],
    'PERMISSION_TYPES'              => [
        'route'    => 'Route',
        'menu'     => 'Menu',
        'app_menu' => 'App Menu',
    ],
    'SUBSCRIPTION_PLAN_TYPES'       => [
        'B2B' => 'B2B',
        'B2C' => 'B2C',
    ],
    'SCHOOL_TYPES'       => [
        '' => '--Select--',
        'individual' => 'Individual',
        'group' => 'Group',
        'demo' => 'Demo',
    ],
    'SCHOOL_TYPES_FOR_FILTER'       => [
        'individual' => 'Individual',
        'group' => 'Group',
        'demo' => 'Demo',
    ],
    'SCHOOL_ROLE'       => [
        'parent' => 'Parent/HO',
        'branch' => 'Branch',
    ],
    'AVAILABLE_TO_USERS'       => [
        'students' => 'Only Students',
        'teachers' => 'Only Teachers',
        'all' => 'All',
    ],
    'DISCOUNT_TYPES'                => [
        'flat'    => 'Flat',
        'percent' => 'Percentage',
    ],
    'USER_TYPES'                => [
        'school_admin'    => 'School ',
        'school_teacher'    => 'Teacher',
        'school_student'    => 'School Student',
        'other' => 'Others',
    ],
    'USER_COME_FOR'                => [
        'for_academic_content'    => 'For Academic Content ',
        'for_talent_content'    => 'For Talent Content',
        'both'    => 'Academic and Talent ( Both ) ',
    ],
    'DURATION_TYPES'                => [
        ['id' => 1, 'days' => 7, 'value' => 'weekly', 'label' => 'Weekly', 'status' => 1],
        ['id' => 2, 'days' => 15, 'value' => 'biweekly', 'label' => 'Biweekly (15 Days)', 'status' => 1], // Added 15-day option
        ['id' => 3, 'days' => 30, 'value' => 'monthly', 'label' => 'Monthly', 'status' => 1],
        ['id' => 4, 'days' => 90, 'value' => 'quarterly', 'label' => 'Quarterly', 'status' => 1],
        ['id' => 5, 'days' => 180, 'value' => 'half_yearly', 'label' => 'Half Yearly', 'status' => 1],
        ['id' => 6, 'days' => 365, 'value' => 'yearly', 'label' => 'Yearly', 'status' => 1],
    ],
    'CHANNEL_TO_PUSH'               => [
        1 => 'Mittlearn',
        2 => 'MittBunny',
        3 => 'Both',
    ],
    'CERTIFICATION_STATUS'          => [
        1 => 'Yes',
        2 => 'No',
    ],
    'YOUR_LICENSE'          => [
        'teachlite' => 'Teachlite (for teachers)',
        'mittlense' => 'MittsureLens (for students)',
    ],
    'DIFFICULTY_LEVEL'              => [
        'easy'   => 'Easy',
        'medium' => 'Medium',
        'hard'   => 'Hard',
    ],
    'CURRENCY_LIST'                 => [
        ["code" => "USD", "symbol" => "$", "name" => "United States Dollar", "status" => 0],
        ["code" => "EUR", "symbol" => "€", "name" => "Euro", "status" => 0],
        ["code" => "GBP", "symbol" => "£", "name" => "British Pound", "status" => 0],
        ["code" => "INR", "symbol" => "₹", "name" => "Indian Rupee", "status" => 1],
        ["code" => "JPY", "symbol" => "¥", "name" => "Japanese Yen", "status" => 0],
        ["code" => "AUD", "symbol" => "A$", "name" => "Australian Dollar", "status" => 0],
        ["code" => "CAD", "symbol" => "C$", "name" => "Canadian Dollar", "status" => 0],
        ["code" => "CHF", "symbol" => "CHF", "name" => "Swiss Franc", "status" => 0],
        ["code" => "CNY", "symbol" => "¥", "name" => "Chinese Yuan", "status" => 0],
        ["code" => "SEK", "symbol" => "kr", "name" => "Swedish Krona", "status" => 0],
        ["code" => "NZD", "symbol" => "NZ$", "name" => "New Zealand Dollar", "status" => 0],
        ["code" => "MXN", "symbol" => "$", "name" => "Mexican Peso", "status" => 0],
        ["code" => "SGD", "symbol" => "S$", "name" => "Singapore Dollar", "status" => 0],
        ["code" => "HKD", "symbol" => "HK$", "name" => "Hong Kong Dollar", "status" => 0],
        ["code" => "NOK", "symbol" => "kr", "name" => "Norwegian Krone", "status" => 0],
        ["code" => "KRW", "symbol" => "₩", "name" => "South Korean Won", "status" => 0],
        ["code" => "TRY", "symbol" => "₺", "name" => "Turkish Lira", "status" => 0],
        ["code" => "RUB", "symbol" => "₽", "name" => "Russian Ruble", "status" => 0],
        ["code" => "BRL", "symbol" => "R$", "name" => "Brazilian Real", "status" => 0],
        ["code" => "ZAR", "symbol" => "R", "name" => "South African Rand", "status" => 0],
        ["code" => "PHP", "symbol" => "₱", "name" => "Philippine Peso", "status" => 0],
        ["code" => "MYR", "symbol" => "RM", "name" => "Malaysian Ringgit", "status" => 0],
        ["code" => "THB", "symbol" => "฿", "name" => "Thai Baht", "status" => 0],
        ["code" => "IDR", "symbol" => "Rp", "name" => "Indonesian Rupiah", "status" => 0],
        ["code" => "VND", "symbol" => "₫", "name" => "Vietnamese Dong", "status" => 0],
        ["code" => "PLN", "symbol" => "zł", "name" => "Polish Zloty", "status" => 0],
        ["code" => "AED", "symbol" => "د.إ", "name" => "United Arab Emirates Dirham", "status" => 0],
        ["code" => "SAR", "symbol" => "﷼", "name" => "Saudi Riyal", "status" => 0],
        ["code" => "EGP", "symbol" => "£", "name" => "Egyptian Pound", "status" => 0],
        ["code" => "NGN", "symbol" => "₦", "name" => "Nigerian Naira", "status" => 0],
        ["code" => "BDT", "symbol" => "৳", "name" => "Bangladeshi Taka", "status" => 0],
    ],
    'FIELD_NAME'                    => [
        1 => 'Basic Information',
        2 => 'Contact Information',
        3 => 'Default Setting',
    ],
    'PREFIX'                        => [
        'M1' => 'AlphabetOnlyWithNumber',
        '1M' => 'NumberWithAlphabetOnly',
        '29' => 'NumberOnly',
        'MB' => 'AlphabetOnly',
        'M@' => 'AlphabetOnlyWithSpecialCharacter',
        '1#' => 'NumberWithSpecialCharacter',
    ],
    'POSTFIX'                       => [
        'M1' => 'AlphabetOnlyWithNumber',
        '1M' => 'NumberWithAlphabetOnly',
        '29' => 'NumberOnly',
        'MB' => 'AlphabetOnly',
        'M@' => 'AlphabetOnlyWithSpecialCharacter',
        '1#' => 'NumberWithSpecialCharacter',
    ],
    'QUESTIONSETUP' => [
        'auto' => 'Auto',
        'manual' => 'Manual',
        'add_new' => 'Add New Question',
    ]
];
